version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./data:/var/lib/mysql
      - ./testdb:/home/test
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 9090:8080
